project_id = "prevtzobwtsnoihwytjg"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[functions.intake]
verify_jwt = false

[functions.search-trigger]
verify_jwt = false